spring:
  datasource:
    url: jdbc:mysql:///learn
    username: root
    password: huhong123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8181